Repository hack4impact-uiuc/love-without-boundaries, pull requests merged in 2018-03, with the labels that each got.

#11 Frontend: Added Redux
  react_frontend/index.js
  react_frontend/package-lock.json
  react_frontend/package.json
  react_frontend/pages/App.js
  react_frontend/redux/actions.js
  react_frontend/redux/reducers.js
  react_frontend/yarn.lock
Labels: Priority: High, Status: In Progress

#12 Addlesson
  react_frontend/components/lesson.js
  react_frontend/components/lessonform.js
  react_frontend/pages/TeacherPage.js
Labels: Status: In Progress

#8 Backend: Adding Quiz Types
  .DS_Store
  web_backend/src/models/answer.js
  web_backend/src/models/question.js
  web_backend/src/models/quiz.js
  web_backend/src/models/student.js
  web_backend/src/schema/mutations/mutation.js
  web_backend/src/schema/queries/query.js
  web_backend/src/schema/types/._InputQuestionType.js
  web_backend/src/schema/types/AnswerType.js
  web_backend/src/schema/types/InputAnswerType.js
  web_backend/src/schema/types/InputQuestionType.js
  web_backend/src/schema/types/QuestionType.js
  web_backend/src/schema/types/QuizType.js
  web_backend/src/schema/types/StudentType.js
Labels: Status: In Progress, Type: Core Feature

#33 Deployment + styling
  .gitignore
  .vscode/launch.json
  react_frontend/.gitignore
  react_frontend/index.html
  react_frontend/index.js
  react_frontend/package.json
  react_frontend/pages/App.js
  react_frontend/pages/HomePage.js
  react_frontend/pages/TeacherPage.js
  react_frontend/webpack.config.js
  react_frontend/yarn.lock
Labels: Priority: Critical, Type: Frontend

#38 Homepage styling
  react_frontend/components/navBar.js
  react_frontend/index.html
  react_frontend/pages/AdminPage.js
  react_frontend/pages/App.js
  react_frontend/pages/HomePage.js
  react_frontend/pages/StudentPage.js
  react_frontend/pages/TeacherPage.js
Labels: Priority: Critical

#1 Backend: Lesson Types
  web_backend/README.md
  web_backend/package-lock.json
  web_backend/package.json
  web_backend/src/index.js
  web_backend/src/models/lessons.js
  web_backend/src/schema/mutations/mutation.js
  web_backend/src/schema/queries/query.js
  web_backend/src/schema/types/LessonType.js
  web_backend/yarn.lock
Labels: Priority: Medium, Status: In Progress, Type: Core Feature
